In [1]:
import pandas as pd
import numpy as np

In [2]:
input_filepath = 'Dati.xlsx'

## Produzioni

Per cartellino (ricetta)

In [3]:
prod_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Produzioni"
)
prod_df_raw.head()

Articolo                         Descrizione  lega  Cartellino    Quantita
0  BIL01330   Billette Euro-HS Diam. 330 CW617N     1           9  18962193.5
1  BIL02210         Billette Prf.Stp. Diam. 210     2           2     36759.3
2  BIL02330  Billette Prf.Stp. Diam. 330 CW612N     2           2   3682923.8
3  BIL04210           Billette MS Pb2 Diam. 210     4           9     10405.8
4  BIL04330    Billette MS Pb2 Diam. 330 CW617N     4           9    990259.7

In [4]:
prod_df = prod_df_raw[['Cartellino', 'Quantita']].groupby('Cartellino').sum().sort_values(['Cartellino']).reset_index()
prod_df.head()

Cartellino    Quantita
0           2   5798032.3
1           7  34993167.0
2           8   7480845.3
3           9  93250827.7
4          14   3751759.6

In [5]:
produzioni = np.array(prod_df['Quantita'])
print(produzioni.shape)
produzioni

(10,)


array([ 5798032.3, 34993167. ,  7480845.3, 93250827.7,  3751759.6,
        1358532.7,   200887.2,  1570139.9,  5013209.2,   285859.1])

## Consumi

Per famiglia

In [6]:
cons_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Consumi"
)
cons_df_raw.head()

Codice Gruppo m  Famiglia  Quantità Codice Materiale  \
0  MP02501    MP140        12   -5380.0              NaN   
1  MP02508    MP160        13   -8846.0              NaN   
2  MP02509    MP140        12 -653965.0              NaN   
3  MP02514    MP166        14   -6542.0              NaN   
4  MP02515    MP155        15   -7392.0              NaN   

   Verifica se il materiale è stato rilevato  
0                                         12  
1                                         13  
2                                         12  
3                                         14  
4                                         15

In [7]:
cons_df = cons_df_raw[['Famiglia', 'Quantità']].groupby('Famiglia').sum().sort_values(['Quantità']).sort_values(['Famiglia']).reset_index()
cons_df['Quantità'] = cons_df['Quantità']*-1
cons_df.head()

Famiglia      Quantità
0         1  1.247382e+06
1         2  7.459129e+07
2         3  3.147928e+06
3         4  1.607647e+06
4         5  7.026350e+04

In [8]:
consumi = np.array(cons_df['Quantità'])
print(consumi.shape)
consumi

(28,)


array([1.24738200e+06, 7.45912877e+07, 3.14792787e+06, 1.60764660e+06,
       7.02635000e+04, 7.18277300e+05, 2.36270000e+04, 3.36220000e+05,
       4.15340593e+07, 2.39488900e+06, 1.41923230e+06, 4.85098600e+05,
       3.38887100e+05, 2.74587000e+04, 2.41829000e+06, 1.17542770e+07,
       3.83755000e+05, 5.17397300e+06, 1.04102070e+07, 1.48622700e+06,
       5.78820000e+04, 2.35000000e+03, 4.44200000e+03, 1.22050000e+04,
       2.43270000e+04, 2.13000000e+02, 6.39550000e+03, 1.08430000e+04])

## Cartellino standard (ricetta)

In [9]:
cart_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Cartellino Standard"
)

cart_df_raw = cart_df_raw[cart_df_raw['Cartellino'].isin(prod_df['Cartellino'])]
cart_df_raw = cart_df_raw[cart_df_raw['Famiglia'].isin(cons_df['Famiglia'])]

cart_df_raw.head()

Cartellino  Famiglia      Descrizione famiglia  Percentuale
0           9       1.0        Rottame ott. misto          0.0
1           9       2.0        Tornitura Euro/pb3         41.5
2           9      12.0  Sfridi/Spezzoni Euro/Pb3         28.4
3           9      20.0              Pani Ot Euro          3.0
4           9      42.0                      Rame         23.8

In [10]:
cart_df = cart_df_raw[['Cartellino', 'Famiglia', 'Percentuale']].reset_index().pivot_table(
    index=['Famiglia'],
    columns=['Cartellino'],
    values='Percentuale'
).fillna(0)

print(cart_df.shape)
cart_df

(28, 10)


Cartellino    2     7     8      9     14    15    18     19     28    38
Famiglia                                                                 
1.0          0.0   3.0   0.0   0.00   0.0   0.0   0.0   0.00   0.00   0.0
2.0         46.0  45.0   5.0  41.50   0.0   0.0   0.0   0.00   1.90   0.0
3.0          0.0   0.0  28.6   0.00   0.0   0.0   0.0   0.00   0.00   0.0
4.0          0.0   0.0   0.0   0.00  40.0   0.0   0.0   0.00  40.00   0.0
5.0          0.0   0.0   0.0   0.00   0.0  38.0   0.0   0.00   0.00   0.0
7.0          0.0   0.0   0.0   0.00   0.0   0.0   0.0  39.70   0.00   0.0
9.0          0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   0.00   1.0
11.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   5.00   0.0
12.0        30.0  21.0   5.0  28.40   0.0   0.0   0.0   0.00   0.50   0.0
13.0         0.0   0.0  30.0   0.00   6.0   2.0   0.0   0.00   0.00   0.0
14.0         0.0   0.0   0.0   0.00  24.9   0.0  83.2  13.75  41.80   0.0
15.0         0.0   0.0   0.0   0.00   0.0  35.7   0.0   0.00   0.00   0.0
17.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0  40.00   0.00   0.0
19.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   0.00   1.0
20.0        10.0  15.0   0.0   3.00   0.0   0.0   0.0   0.00   0.00   0.0
31.0         0.7   0.7   8.5   1.10  10.0   4.0   7.8   2.70   3.20  32.0
35.0         0.0   8.0  15.0   1.02   0.0   7.4   2.0   0.50   0.00   0.0
41.0         0.0   0.0   7.0   0.08   6.3   3.8   6.7   2.40   2.05  55.8
42.0        13.3   7.3   0.0  23.80   0.0   0.0   0.0   0.00   0.00   0.0
51.0         0.0   0.0   0.0   0.00   1.0   0.0   0.0   0.00   0.00   0.0
52.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   2.05   0.0
56.0         0.0   0.0   0.0   0.00   0.0   0.0   0.3   0.00   0.00   0.2
57.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.10   0.00   0.0
60.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.10   0.00  10.0
61.0         0.0   0.0   0.9   0.00   1.8   0.4   0.0   0.50   0.00   0.0
62.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.05   0.00   0.0
71.0         0.0   0.0   0.0   0.00  10.0   8.0   0.0   0.00   3.50   0.0
72.0         0.0   0.0   0.0   0.00   0.0   0.7   0.0   0.20   0.00   0.0

In [11]:
ricette = np.array(cart_df).flatten()

## Composizioni famiglia

In [94]:
comp_raw = pd.read_excel(
    input_filepath,
    sheet_name="Analisi IN FAM"
)
comp_raw = comp_raw.drop(columns=["Media di Totale"])
comp_raw = comp_raw[comp_raw['Etichette di riga'].isin(cons_df['Famiglia'])]
comp_raw = comp_raw.set_index('Etichette di riga')
comp_raw.head()

Media di Cu  Media di Pb  Media di Sn  Media di Fe  \
Etichette di riga                                                       
1                       60.210        1.830        0.440         0.29   
2                       58.500        2.055        0.215         0.24   
3                       61.800        1.720        0.100         0.11   
4                       60.935        0.195        0.125         0.06   
5                       63.900        1.300        0.190         0.13   

                   Media di Ni  Media di Al  Media di Mn  Media di Si  \
Etichette di riga                                                       
1                        0.340          0.1         0.01         0.01   
2                        0.080          0.0         0.00         0.00   
3                        0.040          0.0         0.00         0.00   
4                        0.015          0.0         0.00         0.00   
5                        0.060          0.0         0.00         0.00   

                   Media di As  Media di Sb  Media di Cd  Media di altri  \
Etichette di riga                                                          
1                         0.01         0.01         0.01             0.0   
2                         0.00         0.00         0.00             0.0   
3                         0.00         0.00         0.00             0.0   
4                         0.00         0.00         0.00             0.0   
5                         0.00         0.00         0.00             0.0   

                   Media di Zn  
Etichette di riga               
1                        36.74  
2                        38.91  
3                        36.23  
4                        38.67  
5                        34.42

In [95]:
# Indici mancanti
a = np.array(comp_raw.reset_index()['Etichette di riga'])
b = np.array(cart_df.reset_index()['Famiglia']).astype(int)

for i in range(len(b)):
    if (b[i] not in a):
        print(b[i])
        comp_raw = comp_raw.reindex(comp_raw.index.values.tolist()+[b[i]]).fillna(0).sort_index()

7
17
56
57


In [96]:
composizioni_famiglia = np.array(comp_raw)
print(composizioni_famiglia.shape)
composizioni_famiglia

(28, 13)


array([[6.02100000e+01, 1.83000000e+00, 4.40000000e-01, 2.90000000e-01,
        3.40000000e-01, 1.00000000e-01, 1.00000000e-02, 1.00000000e-02,
        1.00000000e-02, 1.00000000e-02, 1.00000000e-02, 0.00000000e+00,
        3.67400000e+01],
       [5.85000000e+01, 2.05500000e+00, 2.15000000e-01, 2.40000000e-01,
        8.00000000e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.89100000e+01],
       [6.18000000e+01, 1.72000000e+00, 1.00000000e-01, 1.10000000e-01,
        4.00000000e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.62300000e+01],
       [6.09350000e+01, 1.95000000e-01, 1.25000000e-01, 6.00000000e-02,
        1.50000000e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.86700000e+01],
       [6.39000000e+01, 1.30000000e+