In [1]:
import pandas as pd
import numpy as np

In [2]:
input_filepath = 'Dati.xlsx'

## Produzioni

Per cartellino (ricetta)

In [3]:
prod_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Produzioni"
)
prod_df_raw.head()

Articolo                         Descrizione  lega  Cartellino    Quantita
0  BIL01330   Billette Euro-HS Diam. 330 CW617N     1           9  18962193.5
1  BIL02210         Billette Prf.Stp. Diam. 210     2           2     36759.3
2  BIL02330  Billette Prf.Stp. Diam. 330 CW612N     2           2   3682923.8
3  BIL04210           Billette MS Pb2 Diam. 210     4           9     10405.8
4  BIL04330    Billette MS Pb2 Diam. 330 CW617N     4           9    990259.7

In [4]:
prod_df = prod_df_raw[['Cartellino', 'Quantita']].groupby('Cartellino').sum().sort_values(['Cartellino'])
prod_df

# prod_df.to_clipboard(excel=True,sep='\t',  decimal=',')

In [5]:
produzioni = np.array(prod_df['Quantita'])
print(produzioni.shape)
produzioni

(10,)


array([ 5798032.3, 34993167. ,  7480845.3, 93250827.7,  3751759.6,
        1358532.7,   200887.2,  1570139.9,  5013209.2,   285859.1])

## Consumi

Per famiglia

In [6]:
cons_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Consumi"
)
cons_df_raw.head()

Codice Gruppo m  Famiglia Quantità Codice Materiale  \
0  MP02501    MP140      12.0    -5380              NaN   
1  MP02508    MP160      13.0    -8846              NaN   
2  MP02509    MP140      12.0  -653965              NaN   
3  MP02514    MP166      14.0    -6542              NaN   
4  MP02515    MP155      15.0    -7392              NaN   

   Verifica se il materiale è stato rilevato  
0                                       12.0  
1                                       13.0  
2                                       12.0  
3                                       14.0  
4                                       15.0

In [7]:
cons_df = cons_df_raw[['Famiglia', 'Quantità']].groupby('Famiglia').sum().sort_values(['Quantità']).sort_values(['Famiglia'])
cons_df['Quantità'] = cons_df['Quantità']*-1
cons_df

# cons_df.to_clipboard(excel=True,sep='\t',  decimal=',')

Quantità
Famiglia              
1.0            1247382
2.0       74591287.726
3.0        3147927.874
4.0          1607646.6
5.0            70263.5
7.0           718277.3
9.0              23627
11.0            336220
12.0       41534059.34
13.0         2394889.0
14.0         1419232.3
15.0          485098.6
17.0          338887.1
19.0           27458.7
20.0           2418290
31.0          11754277
35.0            383755
41.0           5173973
42.0          10410207
51.0           1486227
52.0             57882
56.0              2350
57.0              4442
60.0             12205
61.0             24327
62.0               213
71.0            6395.5
72.0             10843

In [8]:
consumi = np.array(cons_df['Quantità'])
print(consumi.shape)
np.sum(consumi)
consumi

(28,)


array([1247382, 74591287.72600001, 3147927.8739999994, 1607646.6, 70263.5,
       718277.2999999999, 23627, 336220, 41534059.33999998, 2394889.0,
       1419232.3000000005, 485098.60000000003, 338887.1,
       27458.700000000004, 2418290, 11754277, 383755, 5173973, 10410207,
       1486227, 57882, 2350, 4442, 12205, 24327, 213, 6395.5, 10843],
      dtype=object)

## Cartellino standard (ricetta)

In [9]:
cart_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Cartellino STANDARD Partenza",
    # sheet_name="Cartellino consuntivo",
    # header=1
)

cart_df_raw = cart_df_raw[cart_df_raw['Cartellino'].isin(prod_df.index)]
cart_df_raw = cart_df_raw[cart_df_raw['Famiglia'].isin(cons_df.index)]

cart_df_raw

Cartellino  Famiglia        Descrizione famiglia  Percentuale
0             9       1.0          Rottame ott. misto          0.0
1             9       2.0          Tornitura Euro/pb3         47.5
2             9      12.0    Sfridi/Spezzoni Euro/Pb3         27.0
3             9      20.0                Pani Ot Euro          4.0
4             9      42.0                        Rame         15.0
..          ...       ...                         ...          ...
175          38      31.0                       Zinco          3.5
176          38      60.0               Prolega CU-SI         10.0
178          38      56.0                Prolega CU-P          0.2
179          38      19.0      Sfrdi/Spezzoni SIBRASS          1.0
180          38       4.0  Tornitura LFB-CZLL-OT60/40          NaN

[95 rows x 4 columns]

In [10]:
cart_df = cart_df_raw[['Cartellino', 'Famiglia', 'Percentuale']].reset_index().pivot_table(
    index=['Famiglia'],
    columns=['Cartellino'],
    values='Percentuale'
).fillna(0)

print(cart_df.shape)
cart_df

# cart_df.to_clipboard(excel=True,sep='\t',  decimal=',')

(28, 10)


Cartellino    2     7      8     9     14     15    18     19     28    38
Famiglia                                                                  
1.0          0.0   2.9   0.00   0.0   0.0   0.00   0.0   0.00   0.00   0.0
2.0         45.5  48.0   3.00  47.5   0.0   0.00   0.0   0.00   0.50   0.0
3.0          0.0   0.0  37.75   0.0   5.0   0.00   0.0   0.00   0.00   0.0
4.0          0.0   0.0   0.00   0.0  30.0   0.00   0.0   0.00  40.00   0.0
5.0          0.0   0.0   0.00   0.0   0.0  50.39   0.0   0.00   0.00   0.0
7.0          0.0   0.0   0.00   0.0   0.0   0.00   0.0  37.60   0.00   0.0
9.0          0.0   0.0   0.00   0.0   0.0   0.00   0.0   0.00   0.00   1.0
11.0         0.0   0.0   0.00   0.0   0.0   0.00   0.0   0.00   4.35   0.0
12.0        26.0  19.5   3.00  27.0   0.0   0.00   0.0   0.00   0.50   0.0
13.0         0.0   0.0  30.30   0.0   2.6   1.50   0.0   0.00   0.00   0.0
14.0         0.0   0.0   0.00   0.0  29.6   0.00  53.0  13.75  40.12   0.0
15.0         0.0   0.0   0.00   0.0   0.0  41.50   0.0   0.00   0.00   0.0
17.0         0.0   0.0   0.00   0.0   0.0   0.00   0.0  37.60   0.00   0.0
19.0         0.0   0.0   0.00   0.0   0.0   0.00   0.0   0.00   0.00   1.0
20.0        12.0  10.0   0.00   4.0   0.0   0.00   0.0   0.00   0.00   0.0
31.0         3.0   2.1   4.20   2.5   8.3   0.80   9.5   1.90   2.80   3.5
35.0         0.0   8.0   4.00   0.5   0.0   0.60   0.7   0.50   0.00   0.0
41.0         0.0   0.0  12.80   1.0  19.7   3.60  36.5   8.00   8.25  84.3
42.0        13.5   6.5   4.00  15.0   0.0   0.00   0.0   0.00   0.00   0.0
51.0         0.0   0.0   0.00   0.0   1.0   0.00   0.0   0.00   0.00   0.0
52.0         0.0   0.0   0.00   0.0   0.0   0.00   0.0   0.00   2.60   0.0
56.0         0.0   0.0   0.00   0.0   0.0   0.00   0.3   0.00   0.00   0.2
57.0         0.0   0.0   0.00   0.0   0.0   0.00   0.0   0.10   0.00   0.0
60.0         0.0   0.0   0.00   0.0   0.0   0.00   0.0   0.31   0.00  10.0
61.0         0.0   0.0   0.95   0.0   1.8   0.11   0.0   0.19   0.00   0.0
62.0         0.0   0.0   0.00   0.0   0.0   0.00   0.0   0.05   0.00   0.0
71.0         0.0   0.0   0.00   0.0   3.0   0.70   0.0   0.00   0.88   0.0
72.0         0.0   0.0   0.00   0.0   0.0   0.80   0.0   0.00   0.00   0.0

In [11]:
ricette = np.array(cart_df).flatten()/100
ricette

array([0.000e+00, 2.900e-02, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 4.550e-01, 4.800e-01,
       3.000e-02, 4.750e-01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       5.000e-03, 0.000e+00, 0.000e+00, 0.000e+00, 3.775e-01, 0.000e+00,
       5.000e-02, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 3.000e-01, 0.000e+00,
       0.000e+00, 0.000e+00, 4.000e-01, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 5.039e-01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 3.760e-01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e-02, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       4.350e-02, 0.000e+00, 2.600e-01, 1.950e-01, 

## Composizioni famiglia

In [12]:
comp_raw = pd.read_excel(
    input_filepath,
    sheet_name="Analisi IN FAM",
    header=2
)
comp_raw = comp_raw.drop(columns=["Media di Totale"])
comp_raw = comp_raw[comp_raw['Etichette di riga'].isin(cons_df.index)]
comp_raw = comp_raw.set_index('Etichette di riga')
comp_raw

Media di Cu  Media di Pb  Media di Sn  Media di Fe  \
Etichette di riga                                                       
1                    60.210000     1.830000     0.440000       0.2900   
2                    58.500000     2.055000     0.215000       0.2400   
3                    61.800000     1.720000     0.100000       0.1100   
4                    60.935000     0.195000     0.125000       0.0600   
5                    63.900000     1.300000     0.190000       0.1300   
9                    77.250000     0.100000     0.010000       0.0500   
11                   65.100000     0.010000     1.140000       0.0200   
12                   29.250000     1.250000     0.077500       0.0875   
13                   61.770000     1.720000     0.090000       0.1000   
14                   60.456667     0.113333     0.090000       0.0500   
15                   64.100000     1.300000     0.145000       0.0950   
19                   77.250000     0.100000     0.010000       0.0500   
20                   58.140000     2.540000     0.310000       0.3200   
31                    0.066667     0.380000     0.093333       0.0300   
35                    0.000000    99.900000     0.000000       0.0000   
41                   49.750000     0.025000     0.025000       0.0250   
42                   99.000000     0.235000     0.070000       0.0700   
51                   68.042500     0.010000     0.000000       0.0200   
52                   85.040000     0.010000     0.000000       0.0200   
60                    1.000000     0.000000     0.000000       0.0000   
61                   70.000000     0.000000     0.000000       0.0000   
62                   50.000000     0.000000     0.000000       0.0000   
71                    0.000000     0.000000    99.990000       0.0000   
72                    0.000000     0.000000     0.000000       0.0000   
56                   85.000000     0.000000     0.000000       0.0000   
57                   98.000000     0.000000     0.000000       0.0000   
7                    65.150000     0.560000     0.040000       0.0600   
17                   65.470000     0.490000     0.040000       0.0500   

                   Media di Ni  Media di Al  Media di Mn  Media di Si  \
Etichette di riga                                                       
1                     0.340000         0.10         0.01         0.01   
2                     0.080000         0.00         0.00         0.00   
3                     0.040000         0.00         0.00         0.00   
4                     0.015000         0.00         0.00         0.00   
5                     0.060000         0.00         0.00         0.00   
9                     0.020000         0.00         0.00         0.00   
11                    0.170000         0.00         0.00         0.00   
12                    0.027500         0.00         0.00         0.00   
13                    0.030000         0.00         0.00         0.00   
14                    0.010000         0.00         0.00         0.00   
15                    0.030000         0.00         0.00         0.00   
19                    0.020000         0.00         0.00         0.00   
20                    0.160000         0.02         0.00         0.00   
31                    0.006667         0.05         0.00         0.00   
35                    0.000000         0.00         0.00         0.00   
41                    0.000000         0.00         0.00         0.00   
42                    0.030000         0.01         0.01         0.01   
51                    0.000000         0.00         0.00         0.00   
52                    0.000000         0.00         0.00         0.00   
60                    0.000000         0.00         0.00        99.00   
61                    0.000000         0.00         0.00         0.00   
62                    0.000000        50.00         0.00         0.00   
71                    0.000000         0.00         0.00         0.00   
72 

In [13]:
# Indici mancanti
# a = np.array(comp_raw.reset_index()['Etichette di riga'])
# b = np.array(cart_df.reset_index()['Famiglia']).astype(int)

# for i in range(len(b)):
#     if (b[i] not in a):
#         print(b[i])
#         comp_raw = comp_raw.reindex(comp_raw.index.values.tolist()+[b[i]]).fillna(0).sort_index()

In [14]:
composizioni_famiglia = np.array(comp_raw)
print(composizioni_famiglia.shape)
composizioni_famiglia = composizioni_famiglia.flatten()/100
composizioni_famiglia

(28, 13)


array([6.02100000e-01, 1.83000000e-02, 4.40000000e-03, 2.90000000e-03,
       3.40000000e-03, 1.00000000e-03, 1.00000000e-04, 1.00000000e-04,
       1.00000000e-04, 1.00000000e-04, 1.00000000e-04, 0.00000000e+00,
       3.67400000e-01, 5.85000000e-01, 2.05500000e-02, 2.15000000e-03,
       2.40000000e-03, 8.00000000e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.89100000e-01, 6.18000000e-01, 1.72000000e-02,
       1.00000000e-03, 1.10000000e-03, 4.00000000e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.62300000e-01, 6.09350000e-01,
       1.95000000e-03, 1.25000000e-03, 6.00000000e-04, 1.50000000e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.86700000e-01,
       6.39000000e-01, 1.30000000e-02, 1.90000000e-03, 1.30000000e-03,
      

## Valore atteso materiale per ricetta

In [15]:
att_raw = pd.read_excel(
    input_filepath,
    sheet_name="Toll Fonderia Medio",
    header=1,
    usecols='A,AC:AO'
)
att_raw = att_raw.loc[att_raw['lega'].isin(prod_df.index)]
att_raw = att_raw.set_index('lega')
print(att_raw.shape)
att_raw

(10, 13)


Cu.2  Pb.2   Sn.2   Fe.2   Ni.2   Al.2   Mn.2   Si.2   As.2    Sb.2  \
lega                                                                         
2     59.40  2.05  0.165  0.150  0.050  0.015  0.010  0.005  0.010  0.0075   
7     58.00  2.90  0.165  0.165  0.100  0.015  0.010  0.005  0.010  0.0075   
8     61.80  2.00  0.065  0.065  0.050  0.015  0.010  0.005  0.100  0.0075   
9     58.40  2.05  0.165  0.165  0.050  0.015  0.010  0.005  0.010  0.0075   
14    62.50  0.20  0.100  0.065  0.050  0.015  0.010  0.005  0.100  0.0075   
15    63.70  1.40  0.210  0.065  0.050  0.600  0.010  0.005  0.070  0.0075   
18    62.45  0.21  0.100  0.225  0.025  0.015  0.010  0.000  0.010  0.0075   
19    65.00  0.50  0.100  0.050  0.025  0.125  0.010  0.200  0.065  0.0000   
28    58.35  0.20  0.280  0.070  0.050  0.015  0.005  0.005  0.010  0.0050   
38    76.00  0.05  0.150  0.150  0.100  0.025  0.025  3.100  0.000  0.0075   

       Cd.2  altri.2     Zn.2  
lega                           
2     0.005    0.000  38.1325  
7     0.005    0.000  38.6175  
8     0.005    0.000  35.8775  
9     0.005    0.000  39.1175  
14    0.005    0.001  36.9415  
15    0.005    0.000  33.8775  
18    0.005    0.100  36.8425  
19    0.005    0.001  33.9190  
28    0.005    0.000  41.0050  
38    0.005    0.060  20.3275

In [16]:
a = np.array(att_raw.reset_index()['lega'])
b = np.array(prod_df.index).astype(int)

for i in range(len(b)):
    if (b[i] not in a):
        print(b[i])
        att_raw = att_raw.reindex(att_raw.index.values.tolist()+[b[i]]).fillna(0).sort_index()

att_raw

Cu.2  Pb.2   Sn.2   Fe.2   Ni.2   Al.2   Mn.2   Si.2   As.2    Sb.2  \
lega                                                                         
2     59.40  2.05  0.165  0.150  0.050  0.015  0.010  0.005  0.010  0.0075   
7     58.00  2.90  0.165  0.165  0.100  0.015  0.010  0.005  0.010  0.0075   
8     61.80  2.00  0.065  0.065  0.050  0.015  0.010  0.005  0.100  0.0075   
9     58.40  2.05  0.165  0.165  0.050  0.015  0.010  0.005  0.010  0.0075   
14    62.50  0.20  0.100  0.065  0.050  0.015  0.010  0.005  0.100  0.0075   
15    63.70  1.40  0.210  0.065  0.050  0.600  0.010  0.005  0.070  0.0075   
18    62.45  0.21  0.100  0.225  0.025  0.015  0.010  0.000  0.010  0.0075   
19    65.00  0.50  0.100  0.050  0.025  0.125  0.010  0.200  0.065  0.0000   
28    58.35  0.20  0.280  0.070  0.050  0.015  0.005  0.005  0.010  0.0050   
38    76.00  0.05  0.150  0.150  0.100  0.025  0.025  3.100  0.000  0.0075   

       Cd.2  altri.2     Zn.2  
lega                           
2     0.005    0.000  38.1325  
7     0.005    0.000  38.6175  
8     0.005    0.000  35.8775  
9     0.005    0.000  39.1175  
14    0.005    0.001  36.9415  
15    0.005    0.000  33.8775  
18    0.005    0.100  36.8425  
19    0.005    0.001  33.9190  
28    0.005    0.000  41.0050  
38    0.005    0.060  20.3275

In [17]:
val_att = np.array(att_raw)
print(val_att.shape)
val_att

(10, 13)


array([[5.94000e+01, 2.05000e+00, 1.65000e-01, 1.50000e-01, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-02, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.81325e+01],
       [5.80000e+01, 2.90000e+00, 1.65000e-01, 1.65000e-01, 1.00000e-01,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-02, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.86175e+01],
       [6.18000e+01, 2.00000e+00, 6.50000e-02, 6.50000e-02, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-01, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.58775e+01],
       [5.84000e+01, 2.05000e+00, 1.65000e-01, 1.65000e-01, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-02, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.91175e+01],
       [6.25000e+01, 2.00000e-01, 1.00000e-01, 6.50000e-02, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-01, 7.50000e-03,
        5.00000e-03, 1.00000e-03, 3.69415e+01],
       [6.37000e+01, 1.40000e+

In [18]:
val_att

range_ric_mat = np.full((val_att.shape[0],val_att.shape[1]), None, dtype='f,f')

for iy, ix in np.ndindex(val_att.shape):
    range_ric_mat[iy, ix] = (val_att[iy, ix]/100 if val_att[iy,ix] != 0 else 0, 0.01)

print(range_ric_mat.shape)
range_ric_mat

(10, 13)


array([[(5.94000e-01, 0.1), (2.05000e-02, 0.1), (1.65000e-03, 0.1),
        (1.50000e-03, 0.1), (5.00000e-04, 0.1), (1.50000e-04, 0.1),
        (1.00000e-04, 0.1), (5.00000e-05, 0.1), (1.00000e-04, 0.1),
        (7.50000e-05, 0.1), (5.00000e-05, 0.1), (0.00000e+00, 0.1),
        (3.81325e-01, 0.1)],
       [(5.80000e-01, 0.1), (2.90000e-02, 0.1), (1.65000e-03, 0.1),
        (1.65000e-03, 0.1), (1.00000e-03, 0.1), (1.50000e-04, 0.1),
        (1.00000e-04, 0.1), (5.00000e-05, 0.1), (1.00000e-04, 0.1),
        (7.50000e-05, 0.1), (5.00000e-05, 0.1), (0.00000e+00, 0.1),
        (3.86175e-01, 0.1)],
       [(6.18000e-01, 0.1), (2.00000e-02, 0.1), (6.50000e-04, 0.1),
        (6.50000e-04, 0.1), (5.00000e-04, 0.1), (1.50000e-04, 0.1),
        (1.00000e-04, 0.1), (5.00000e-05, 0.1), (1.00000e-03, 0.1),
        (7.50000e-05, 0.1), (5.00000e-05, 0.1), (0.00000e+00, 0.1),
        (3.58775e-01, 0.1)],
       [(5.84000e-01, 0.1), (2.05000e-02, 0.1), (1.65000e-03, 0.1),
        (1.65000e-03, 0.1), (